version: '3.10.11'
services:
 app:
  build: .
  volumes:
   - .:/social_media_site
  ports:
   - 8000:8000
  image: app:social_media_site
  container_name: social_media_platform
  command: python manage.py runserver 0.0.0.0:8000
