from core.test_cases.post_details_test_cases import PostDetailsViewTestCase
from core.test_cases.post_create_test_cases import PostCreateViewTestCase
from core.test_cases.urls_test_cases import UrlsTestCase